
import React from 'react';
import { Language } from './types';

export const TRANSLATIONS = {
  [Language.EN]: {
    appName: 'StallMate',
    ordering: 'Ordering',
    inventory: 'Inventory',
    analytics: 'Analytics',
    records: 'Records',
    settings: 'Settings',
    total: 'Total',
    checkout: 'Checkout',
    addToCart: 'Add to Cart',
    cash: 'Cash',
    payme: 'PayMe',
    alipay: 'Alipay',
    fps: 'FPS',
    confirmPayment: 'Confirm Payment',
    scanToPay: 'Scan to Pay',
    dailyReport: 'Daily Report',
    profit: 'Profit',
    revenue: 'Revenue',
    stockLevel: 'Stock Level',
    aiScan: 'Smart Scan Inventory',
    uploadPhoto: 'Upload Label/Invoice',
    extracting: 'Extracting Details...',
    noProducts: 'No products in stock.',
    stockOutAlert: 'Stock Low Alert!',
    bestSellers: 'Best Selling Items',
    noRecords: 'No transactions yet.',
    history: 'History',
    driveFolder: 'Drive Folder',
    selectDrive: 'Connect Google Drive',
    cameraRoll: 'Camera Roll',
    priceModified: 'Price Modified',
    stockModified: 'Stock Modified',
    saveChanges: 'Save Changes',
    editProduct: 'Edit Product',
    stockThreshold: 'Stock Alert Threshold',
    telegramSettings: 'Telegram Alert Config',
    botToken: 'Bot Token',
    chatId: 'Chat ID',
    notificationPref: 'Notification Preferences',
    notifNone: 'No Notifications',
    notifTransaction: 'Detailed Transaction Records',
    notifStock: 'Stock Less Than Threshold (Low Stock)',
    notifBoth: 'Both Records & Stock Alerts',
    transactionCount: 'Total Transactions',
    newCustomers: 'New Customers',
    refundCount: 'Total Refunds',
    cashReceived: 'Cash Received',
    changeDue: 'Change Due',
    dailySettlement: 'Daily Settlement',
    settlementTime: 'Auto-Settlement Time',
    enableAutoSettlement: 'Enable Auto Settlement',
    settleNow: 'Settle & Export Now',
    settlementDescription: 'Generate Excel reports automatically at the chosen time.',
    refund: 'Refund',
    refundItems: 'Select Items to Refund',
    refundReason: 'Reason for Refund',
    refundMethod: 'Refund Method',
    processRefund: 'Confirm Refund',
    refunded: 'Refunded',
    partialRefund: 'Partial Refund',
    reasonDamaged: 'Damaged Item',
    reasonCustomer: 'Customer Changed Mind',
    reasonMistake: 'Order Mistake',
    reasonOther: 'Other Reason'
  },
  [Language.ZH]: {
    appName: '揸流攤',
    ordering: '點餐系統',
    inventory: '庫庫管理',
    analytics: '數據分析',
    records: '銷售記錄',
    settings: '設置',
    total: '總計',
    checkout: '結帳',
    addToCart: '加入購物車',
    cash: '現金',
    payme: 'PayMe',
    alipay: '支付寶',
    fps: '轉數快',
    confirmPayment: '確認收款',
    scanToPay: '請掃碼支付',
    dailyReport: '每日報表',
    profit: '利潤',
    revenue: '營業額',
    stockLevel: '庫存水平',
    aiScan: '智能掃描入庫',
    uploadPhoto: '上傳標籤/發票',
    extracting: '正在提取信息...',
    noProducts: '目前沒有庫存。',
    stockOutAlert: '庫存不足警報！',
    bestSellers: '暢銷產品',
    noRecords: '尚無交易記錄。',
    history: '修改歷史',
    driveFolder: '雲端資料夾',
    selectDrive: '連接 Google Drive',
    cameraRoll: '相簿上傳',
    priceModified: '價格已修改',
    stockModified: '庫存已修改',
    saveChanges: '保存更改',
    editProduct: '編輯產品',
    stockThreshold: '庫存預警臨界值',
    telegramSettings: 'Telegram 警報設置',
    botToken: '機器人 Token',
    chatId: '聊天 ID',
    notificationPref: '通知偏好設置',
    notifNone: '關閉所有通知',
    notifTransaction: '每一筆詳細交易記錄',
    notifStock: '庫存低於預警值 (15% 警報)',
    notifBoth: '交易記錄及庫存警報',
    transactionCount: '交易總數',
    newCustomers: '新客數量',
    refundCount: '退款總數',
    cashReceived: '實收現金',
    changeDue: '應找回',
    dailySettlement: '每日結算',
    settlementTime: '自動結算時間',
    enableAutoSettlement: '開啟自動結算',
    settleNow: '立即結算並導出',
    settlementDescription: '在指定時間自動生成並導出 Excel 營業報表。',
    refund: '退款',
    refundItems: '選擇退款項目',
    refundReason: '退款原因',
    refundMethod: '退款方式',
    processRefund: '確認退款',
    refunded: '已退款',
    partialRefund: '部分退款',
    reasonDamaged: '商品損壞',
    reasonCustomer: '顧客改變主意',
    reasonMistake: '下單錯誤',
    reasonOther: '其他原因'
  }
};

export const PAYMENT_QR_CODES = {
  PAYME: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=PayMe_Mock_Endpoint',
  ALIPAY: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=Alipay_Mock_Endpoint',
  FPS: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=FPS_Mock_Endpoint'
};
